# ── Perfil ESPAÑOL (navbar completo) ──
project:
  render:
    - index.qmd
    - profesional.qmd

website:
  title: "Tu Nombre"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Información profesional"
        href: profesional.qmd
    right:
      - icon: translate
        menu:
          - text: "Español"
            href: index.qmd
          - text: "English"
            href: en/index.qmd

lang: es
